server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Notification?createDatabaseIfNotExist=true
    #url: jdbc:mysql://mysql-auth-server:3306/OAuthDB?createDatabaseIfNotExist=true
    username: root
    password: sudi
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
